### ISSUE TITLE
Dynamisch aktualisierende Spendenanzeige (Startnext)

### ISSUE THREAD

**Issue by hutt** [Sanktionsfrei/Onepager#6]

**Comment by ZengineChris** [comment]
Brauche ich hier irgendwelche Zugangsdaten? Wo finde ich die Doku zu der API? @77u4

**Comment by ZengineChris** [comment]
Soweit ich das jetzt weiß gibt es keine API mit der man einen Status eines Spendenbalkens abrufen kann. Lediglich ein Widget was man in die Seite einbetten kann.

**Comment by hutt** [comment]
(siehe Slack)
